### ISSUE TITLE
Special names in windows api

### ISSUE THREAD

**Issue by myCrack** [johnwinans/rvddt#3]
You have file `src/dev/con.h`, but windows disallows¹ that name. So can you rename it?

---
¹ https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions
>* Do not use the following reserved names for the name of a file:
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended.

**Comment by johnwinans** [comment]
Glad to see that they support the CP/M device name API... from the '70s.

:-)
